import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, AlertOctagon, ArrowDownRight, ArrowUpRight, Bell, Check, ChevronDown, CircleHelp, Clock3, Command, Download, Filter, Gauge, Globe2, LayoutDashboard, Menu, RefreshCw, Search, Shield, ShieldAlert, ShieldCheck, SlidersHorizontal, Terminal, Wifi, X } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, BarChart, Bar } from 'recharts';
import { api } from './api';
import './styles.css';

const SEVERITY = { critical: '#ff5570', high: '#ff9d57', medium: '#f6c85f', low: '#58b9f4', info: '#9aa9c4' };
const fmtTime = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : new Intl.DateTimeFormat('en-US', { hour: '2-digit', minute: '2-digit', month: 'short', day: 'numeric' }).format(date); };
const shortNum = (n) => new Intl.NumberFormat('en-US', { notation: n > 999 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(n ?? 0);

function App() {
  const [alerts, setAlerts] = useState([]); const [summary, setSummary] = useState(null); const [trends, setTrends] = useState([]); const [types, setTypes] = useState([]);
  const [search, setSearch] = useState(''); const [severity, setSeverity] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [selected, setSelected] = useState(null);
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(''); const [lastUpdated, setLastUpdated] = useState(new Date()); const [toast, setToast] = useState(''); const [showCreate, setShowCreate] = useState(false);
  const load = useCallback(async (quiet = false) => {
    quiet ? setRefreshing(true) : setLoading(true); setError('');
    try { const [a,s,t,ty] = await Promise.all([api.alerts({ q: search, severity, status: statusFilter, limit: 200 }), api.summary(), api.trends(7), api.types()]); setAlerts(a); setSummary(s); setTrends(t); setTypes(ty); setLastUpdated(new Date()); }
    catch (e) { setError(`${e.message}. Check that the API service is running.`); }
    finally { setLoading(false); setRefreshing(false); }
  }, [search, severity, statusFilter]);
  useEffect(() => { const timer = setTimeout(() => load(), 180); return () => clearTimeout(timer); }, [load]);
  useEffect(() => { const id = setInterval(() => load(true), 30000); return () => clearInterval(id); }, [load]);
  const criticalOpen = summary?.critical ?? 0;
  const typeData = useMemo(() => types.slice(0, 5).map((x) => ({ name: x.type, value: x.count })), [types]);
  async function changeStatus(alert, next) { try { await api.updateAlert(alert.id, { status: next, assignee: alert.assignee || null }); setToast(`Alert marked ${next.replace('_', ' ')}.`); setSelected(null); await load(true); setTimeout(() => setToast(''), 3000); } catch (e) { setError(e.message); } }
  function exportCsv() { const headers = ['id','title','severity','alert_type','status','source_ip','host','detector','created_at']; const quote = (v) => `"${String(v ?? '').replaceAll('"','""')}"`; const rows = [headers.join(','), ...alerts.map(a => headers.map(h => quote(a[h])).join(','))].join('\n'); const url = URL.createObjectURL(new Blob([rows], {type:'text/csv;charset=utf-8;'})); const link = document.createElement('a'); link.href = url; link.download = `sentinel-alerts-${new Date().toISOString().slice(0,10)}.csv`; link.click(); URL.revokeObjectURL(url); }
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Shield size={23}/></div><div><div className="brand-name">SENTINEL<span className="brand-dot">.</span></div><div className="brand-sub">SECURITY OPERATIONS</div></div><button className="icon-button mobile-menu" aria-label="Open menu"><Menu size={18}/></button></div>
      <div className="workspace"><div className="workspace-icon"><Command size={16}/></div><div className="workspace-copy"><strong>Acme Security</strong><span>Enterprise workspace</span></div><ChevronDown size={15} className="muted"/></div>
      <div className="nav-label">WORKSPACE</div><nav className="nav"><a className="nav-item active" href="#overview"><LayoutDashboard size={17}/>Overview<span className="nav-active-dot"/></a><a className="nav-item" href="#alerts"><Bell size={17}/>Alert queue<span className="nav-count">{summary?.open ?? '—'}</span></a><a className="nav-item" href="#analytics"><Activity size={17}/>Analytics</a><a className="nav-item" href="#sources"><Globe2 size={17}/>Detection sources</a></nav>
      <div className="nav-label mt">SYSTEM</div><div className="nav-item subdued"><SlidersHorizontal size={17}/>Configuration</div><div className="nav-item subdued"><CircleHelp size={17}/>Documentation</div>
      <div className="sidebar-bottom"><div className="system-health"><div className="health-head"><span className="live-dot"/>System health</div><div className="health-copy">All systems operational</div><div className="health-meter"><span/></div><div className="health-meta"><span>API latency</span><strong>42 ms</strong></div><div className="health-meta"><span>Ingestion pipeline</span><strong className="ok-text">Healthy</strong></div></div><div className="profile"><div className="avatar">JD</div><div className="profile-copy"><strong>Jordan Davis</strong><span>Security analyst</span></div><ChevronDown size={15} className="muted"/></div></div>
    </aside>
    <main className="main-content"><header className="topbar"><div className="breadcrumbs"><span>Workspace</span><span className="crumb-sep">/</span><strong>Overview</strong></div><div className="top-actions"><div className="environment"><span className="live-dot"/>PRODUCTION</div><div className="top-divider"/><button className="icon-button" title="Refresh data" onClick={() => load(true)}><RefreshCw size={17} className={refreshing ? 'spin' : ''}/></button><button className="icon-button notification" title="Notifications"><Bell size={17}/><i/></button><div className="avatar small-avatar">JD</div></div></header>
      <div className="page-wrap"><section className="page-heading" id="overview"><div><div className="eyebrow"><span className="eyebrow-line"/>THREAT INTELLIGENCE <span className="eyebrow-sep">/</span> OVERVIEW</div><h1>Security overview<span className="heading-period">.</span></h1><p className="subtitle">Monitor, investigate, and respond to threats across your environment.</p></div><div className="heading-actions"><span className="updated"><span className="live-dot"/>Updated {lastUpdated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span><button className="button secondary" onClick={exportCsv}><Download size={15}/> Export report</button><button className="button primary" onClick={() => setShowCreate(true)}><span className="plus">+</span> Create alert</button></div></section>
      {error && <div className="error-banner" role="alert"><AlertOctagon size={18}/><div><strong>Unable to load live data</strong><span>{error}</span></div><button className="icon-button" onClick={() => load()} aria-label="Retry"><RefreshCw size={16}/></button></div>}
      <section className="metrics-grid" aria-label="Alert summary"><Metric icon={<ShieldAlert size={18}/>} label="Total alerts" value={shortNum(summary?.total)} detail="All detected events" tone="blue"/><Metric icon={<AlertOctagon size={18}/>} label="Critical threats" value={shortNum(criticalOpen)} detail="Require immediate action" tone="red" trend="Priority"/><Metric icon={<Clock3 size={18}/>} label="Open investigations" value={shortNum(summary?.open)} detail="Awaiting analyst review" tone="amber"/><Metric icon={<ShieldCheck size={18}/>} label="Resolved alerts" value={shortNum(summary?.resolved)} detail="Closed by the SOC team" tone="green"/></section>
      <section className="charts-grid" id="analytics"><div className="panel trend-panel"><div className="panel-heading"><div><h2>Alert activity</h2><p>Detection volume across the last 7 days</p></div><div className="chart-legend"><span><i className="legend-dot total-dot"/>All alerts</span><span><i className="legend-dot critical-dot"/>Critical</span></div></div><div className="chart-area">{trends.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={trends} margin={{top:12,right:6,left:-18,bottom:0}}><defs><linearGradient id="totalFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#50a8ff" stopOpacity={0.24}/><stop offset="100%" stopColor="#50a8ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#202c40" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="date" tickFormatter={v => new Date(`${v}T00:00:00`).toLocaleDateString('en-US',{weekday:'short'})} tick={{fill:'#8190a9',fontSize:11}} axisLine={false} tickLine={false} dy={9}/><YAxis allowDecimals={false} tick={{fill:'#8190a9',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#101a2b',border:'1px solid #2a3a52',borderRadius:10,color:'#e8eef8'}} labelFormatter={v => new Date(`${v}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}/><Area type="monotone" dataKey="total" name="All alerts" stroke="#50a8ff" strokeWidth={2.3} fill="url(#totalFill)"/><Area type="monotone" dataKey="critical" name="Critical" stroke="#ff5570" strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer> : <EmptyChart loading={loading}/>}</div><div className="chart-foot"><span><span className="live-dot"/>Live event stream</span><span>Auto-refreshes every 30 seconds</span></div></div>
        <div className="panel type-panel" id="sources"><div className="panel-heading"><div><h2>Alerts by type</h2><p>Distribution by detection category</p></div><button className="icon-button subtle-icon" aria-label="Chart options"><SlidersHorizontal size={16}/></button></div><div className="donut-wrap">{typeData.length ? <><ResponsiveContainer width="58%" height="100%"><PieChart><Pie data={typeData} dataKey="value" nameKey="name" innerRadius="66%" outerRadius="88%" paddingAngle={4} stroke="none">{typeData.map((entry,i)=><Cell key={entry.name} fill={['#5caeff','#9b8afb','#53d6bd','#f5b95f','#ff7188'][i%5]}/>)}</Pie><Tooltip contentStyle={{background:'#101a2b',border:'1px solid #2a3a52',borderRadius:10,color:'#e8eef8'}}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{shortNum(summary?.total)}</strong><span>total alerts</span></div><div className="type-legend">{typeData.map((x,i)=><div className="type-legend-row" key={x.name}><span className="type-legend-name"><i style={{background:['#5caeff','#9b8afb','#53d6bd','#f5b95f','#ff7188'][i%5]}}/>{x.name}</span><strong>{x.value}</strong></div>)}</div></> : <EmptyChart loading={loading}/>}</div></div></section>
      <section className="panel alerts-panel" id="alerts"><div className="alerts-heading"><div><div className="title-inline"><h2>Recent alerts</h2><span className="count-pill">{alerts.length}</span></div><p>Review and triage events detected by your security stack.</p></div><button className="text-button" onClick={() => {setSeverity('');setStatusFilter('');setSearch('');}}>Clear filters <X size={14}/></button></div><div className="filter-bar"><label className="search-box"><Search size={16}/><input aria-label="Search alerts" placeholder="Search alerts, IPs, hosts..." value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌘ K</kbd></label><div className="filter-control"><Filter size={15}/><select aria-label="Filter severity" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All severities</option>{['critical','high','medium','low','info'].map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></div><div className="filter-control"><select aria-label="Filter status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option>{['new','investigating','resolved','false_positive'].map(s=><option key={s} value={s}>{s.replace('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}</option>)}</select></div><button className="icon-button filter-icon" aria-label="More filters"><SlidersHorizontal size={16}/></button></div>
      <div className="table-scroll"><table><thead><tr><th>SEVERITY</th><th>ALERT</th><th>TYPE</th><th>SOURCE / HOST</th><th>STATUS</th><th>DETECTED</th><th></th></tr></thead><tbody>{loading && !alerts.length ? <tr><td colSpan="7" className="table-state">Loading alert stream…</td></tr> : alerts.length ? alerts.map(a=><tr key={a.id} onClick={()=>setSelected(a)} className="alert-row"><td><Severity severity={a.severity}/></td><td><div className="alert-title">{a.title}</div><div className="alert-id">#{a.id.slice(0,8).toUpperCase()}</div></td><td><span className="type-tag">{a.alert_type}</span></td><td><div className="source-ip">{a.source_ip}</div><div className="host-name">{a.host}</div></td><td><Status status={a.status}/></td><td><span className="time-value">{fmtTime(a.created_at)}</span></td><td><button className="row-more" aria-label={`View ${a.title}`} onClick={e=>{e.stopPropagation();setSelected(a)}}>···</button></td></tr>) : <tr><td colSpan="7" className="table-state"><ShieldCheck size={24}/><strong>No alerts match your filters</strong><span>Try a different search or clear filters.</span></td></tr>}</tbody></table></div><div className="table-footer"><span>Showing <strong>{alerts.length}</strong> alerts <span className="footer-dot">·</span> Sorted by newest</span><div className="pagination"><button disabled>Previous</button><button className="page-current">1</button><button disabled>Next</button></div></div></section>
      <footer className="footer"><span>© 2026 Sentinel Security Operations</span><span><span className="live-dot"/> All systems operational <i/> API v1.0.0</span></footer>
      </div>
    </main>
    {selected && <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="detail-modal" role="dialog" aria-modal="true" aria-labelledby="detail-title"><div className="modal-head"><div><span className="modal-eyebrow">ALERT DETAILS · {selected.id.slice(0,8).toUpperCase()}</span><h2 id="detail-title">{selected.title}</h2></div><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Close alert details"><X size={18}/></button></div><div className="detail-badges"><Severity severity={selected.severity}/><Status status={selected.status}/><span className="type-tag">{selected.alert_type}</span></div><p className="detail-description">{selected.description}</p><div className="detail-grid"><Detail label="Source IP" value={selected.source_ip}/><Detail label="Affected host" value={selected.host}/><Detail label="Detection rule" value={selected.detector}/><Detail label="First detected" value={fmtTime(selected.created_at)}/><Detail label="Assignee" value={selected.assignee || 'Unassigned'}/></div><div className="modal-actions"><button className="button secondary" onClick={()=>changeStatus(selected,'false_positive')}>Mark false positive</button><button className="button secondary" onClick={()=>changeStatus(selected,'resolved')}><Check size={15}/> Resolve</button>{selected.status!=='investigating'&&<button className="button primary" onClick={()=>changeStatus(selected,'investigating')}>Investigate alert</button>}</div></section></div>}
    {showCreate && <CreateAlert onClose={()=>setShowCreate(false)} onCreated={async()=>{setShowCreate(false);await load(true);setToast('Alert created successfully.');setTimeout(()=>setToast(''),3000)}} onError={setError}/>}
    {toast && <div className="toast" role="status"><Check size={17}/>{toast}</div>}
  </div>;
}
function Metric({icon,label,value,detail,tone,trend}) { return <div className="metric-card"><div className="metric-top"><div className={`metric-icon ${tone}`}>{icon}</div>{trend&&<span className="metric-flag"><span/> {trend}</span>}</div><div className="metric-label">{label}</div><div className="metric-value">{value ?? '—'}</div><div className="metric-detail">{detail}</div></div>; }
function Severity({severity}) { return <span className={`severity severity-${severity}`}><i/>{severity}</span>; }
function Status({status}) { return <span className={`status status-${status}`}><i/>{status.replace('_',' ')}</span>; }
function Detail({label,value}) { return <div className="detail-item"><span>{label}</span><strong>{value}</strong></div>; }
function EmptyChart({loading}) { return <div className="empty-chart">{loading?<><RefreshCw size={18} className="spin"/>Loading analytics…</>:<><Activity size={20}/>No analytics data available</>}</div>; }
function CreateAlert({onClose,onCreated,onError}) { const [form,setForm]=useState({title:'',description:'',severity:'medium',alert_type:'Endpoint Threat',source_ip:'',host:'',detector:'manual'}); const [busy,setBusy]=useState(false); const change=e=>setForm({...form,[e.target.name]:e.target.value}); async function submit(e){e.preventDefault();setBusy(true);try{await api.createAlert(form);await onCreated()}catch(err){onError(err.message)}finally{setBusy(false)}} return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="detail-modal create-modal" onSubmit={submit} role="dialog" aria-modal="true" aria-labelledby="create-title"><div className="modal-head"><div><span className="modal-eyebrow">MANUAL INGESTION</span><h2 id="create-title">Create alert</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close create alert"><X size={18}/></button></div><div className="form-grid"><label className="full-field">Alert title<input required minLength="4" maxLength="180" name="title" value={form.title} onChange={change} placeholder="Suspicious activity detected"/></label><label className="full-field">Description<textarea required minLength="5" maxLength="4000" name="description" value={form.description} onChange={change} placeholder="Describe the signal and why it matters." rows="3"/></label><label>Severity<select name="severity" value={form.severity} onChange={change}>{['critical','high','medium','low','info'].map(x=><option key={x}>{x}</option>)}</select></label><label>Alert type<input required name="alert_type" value={form.alert_type} onChange={change}/></label><label>Source IP<input required name="source_ip" value={form.source_ip} onChange={change} placeholder="192.0.2.10"/></label><label>Affected host<input required name="host" value={form.host} onChange={change} placeholder="endpoint-01"/></label></div><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button type="submit" className="button primary" disabled={busy}>{busy?'Creating…':'Create alert'}</button></div></form></div>; }

export default App;
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
